[2022-01-18 22:54:51,648: INFO: stage_01_get_data]: 
********************
[2022-01-18 22:54:51,648: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-01-18 22:54:51,650: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-18 22:54:51,655: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-18 22:54:51,655: ERROR: stage_01_get_data]: 'course_download_dirs'
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 41, in <module>
    get_data(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_get_data.py", line 24, in get_data
    source_download_dirs = config['course_download_dirs']
KeyError: 'course_download_dirs'
[2022-01-18 22:55:23,367: INFO: stage_01_get_data]: 
********************
[2022-01-18 22:55:23,367: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-01-18 22:55:23,368: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-18 22:55:23,369: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-18 22:55:23,369: ERROR: stage_01_get_data]: 'sourse_download_dirs'
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 41, in <module>
    get_data(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_get_data.py", line 24, in get_data
    source_download_dirs = config['sourse_download_dirs']
KeyError: 'sourse_download_dirs'
[2022-01-18 22:56:18,336: INFO: stage_01_get_data]: 
********************
[2022-01-18 22:56:18,337: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-01-18 22:56:18,338: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-18 22:56:18,338: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-18 22:56:18,366: INFO: common]: created directory at: data/cat
[2022-01-18 22:56:18,367: ERROR: stage_01_get_data]: [WinError 3] The system cannot find the path specified: '../outside_data/cat'
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 41, in <module>
    get_data(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_get_data.py", line 29, in get_data
    copy_files(source_download_dir, local_data_dir)
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\common.py", line 22, in copy_files
    list_of_files = os.listdir(source_download_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '../outside_data/cat'
[2022-01-18 23:12:22,600: INFO: stage_01_get_data]: 
********************
[2022-01-18 23:12:22,600: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-01-18 23:12:22,601: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-18 23:12:22,602: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-18 23:12:22,612: INFO: common]: created directory at: data/cat
[2022-01-18 23:12:53,864: INFO: common]: Copying succeeded!
[2022-01-18 23:12:53,866: INFO: common]: created directory at: data/dog
[2022-01-18 23:13:55,934: INFO: common]: Copying succeeded!
[2022-01-18 23:13:55,935: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME completed!<<<<<

[2022-01-18 23:38:57,954: INFO: stage_01_get_data]: 
********************
[2022-01-18 23:38:57,954: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME started <<<<<
[2022-01-18 23:38:57,956: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-18 23:38:57,956: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-18 23:38:57,966: INFO: common]: created directory at: data/cat
[2022-01-18 23:39:02,837: INFO: common]: Copying succeeded!
[2022-01-18 23:39:02,838: INFO: common]: created directory at: data/dog
[2022-01-18 23:39:12,691: INFO: common]: Copying succeeded!
[2022-01-18 23:39:12,692: INFO: stage_01_get_data]: >>>>> stage STAGE_NAME completed!<<<<<

[2022-01-19 13:05:16,135: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:05:16,145: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:05:16,151: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:05:16,151: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:05:16,151: ERROR: stage_02_prepare_model]: module 'os' has no attribute 'apth'
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 28, in prepare_model
    base_model_dir_path = os.apth.join(artifacts_dir,base_model_dir)
AttributeError: module 'os' has no attribute 'apth'
[2022-01-19 13:05:49,441: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:05:49,441: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:05:49,441: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:05:49,441: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:05:49,441: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:05:49,441: ERROR: stage_02_prepare_model]: 'module' object is not callable
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 34, in prepare_model
    model_path=base_model_path
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\models.py", line 9, in get_VGG16_model
    include_top = False
TypeError: 'module' object is not callable
[2022-01-19 13:10:20,837: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:10:20,837: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:10:20,837: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:10:20,837: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:10:20,849: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:10:20,849: ERROR: stage_02_prepare_model]: 'module' object is not callable
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 34, in prepare_model
    model_path=base_model_path
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\models.py", line 9, in get_VGG16_model
    include_top = False
TypeError: 'module' object is not callable
[2022-01-19 13:11:01,797: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:11:01,797: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:11:01,797: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:11:01,797: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:11:01,797: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:11:01,797: ERROR: stage_02_prepare_model]: VGG16() got multiple values for argument 'include_top'
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 34, in prepare_model
    model_path=base_model_path
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\models.py", line 9, in get_VGG16_model
    include_top = False
TypeError: VGG16() got multiple values for argument 'include_top'
[2022-01-19 13:12:54,492: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:12:54,492: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:12:54,492: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:12:54,492: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:12:54,492: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:13:03,644: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 13:13:03,707: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 13:13:03,707: ERROR: stage_02_prepare_model]: 'module' object is not callable
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 41, in prepare_model
    freeze_till=None
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\models.py", line 36, in prepare_full_model
    loss  = tf.keras.losses('categorical_crossentropy'),
TypeError: 'module' object is not callable
[2022-01-19 13:15:20,691: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:15:20,691: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:15:20,691: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:15:20,691: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:15:20,691: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:15:21,442: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 13:15:21,506: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 13:15:21,521: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 13:15:21,521: ERROR: stage_02_prepare_model]: name 'updated_base_model_path' is not defined
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 45, in prepare_model
    full_model.save(updated_base_model_path)
NameError: name 'updated_base_model_path' is not defined
[2022-01-19 13:15:44,793: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:15:44,793: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:15:44,793: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:15:44,793: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:15:44,793: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:15:45,484: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 13:15:45,563: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 13:15:45,563: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 13:15:45,645: INFO: stage_02_prepare_model]: full untrained model is saved at artifacts\base_model\updated_base_model.h5
[2022-01-19 13:15:45,645: INFO: stage_02_prepare_model]: >>>>> stage preare model completed! : Base model is created.<<<<<

[2022-01-19 13:40:43,738: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 13:40:43,738: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 13:40:43,740: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 13:40:43,741: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 13:40:43,741: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 13:40:44,443: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 13:40:44,520: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 13:40:44,533: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 13:40:44,534: INFO: models]: full model summary Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         
_________________________________________________________________
flatten (Flatten)            (None, 25088)             0         
_________________________________________________________________
dense (Dense)                (None, 2)                 50178     
=================================================================
Total params: 14,764,866
Trainable params: 50,178
Non-trainable params: 14,714,688
_________________________________________________________________

[2022-01-19 13:40:44,603: INFO: stage_02_prepare_model]: full untrained model is saved at artifacts\base_model\updated_base_model.h5
[2022-01-19 13:40:44,604: INFO: stage_02_prepare_model]: >>>>> stage preare model completed! : Base model is created.<<<<<

[2022-01-19 15:20:21,267: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 15:20:21,267: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 15:20:21,269: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 15:20:21,270: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 15:20:21,270: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 15:20:21,998: ERROR: stage_02_prepare_model]: name 'full_model' is not defined
Traceback (most recent call last):
  File "src/stage_02_prepare_model.py", line 58, in <module>
    prepare_model(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_prepare_model.py", line 34, in prepare_model
    model_path=base_model_path
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\models.py", line 22, in get_VGG16_model
    logging.info(f'full model summary {get_model_summary(full_model)}')
NameError: name 'full_model' is not defined
[2022-01-19 15:20:43,603: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 15:20:43,603: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 15:20:43,603: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 15:20:43,603: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 15:20:43,603: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 15:20:44,299: INFO: models]: full model summary Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         
=================================================================
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________

[2022-01-19 15:20:44,299: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 15:20:44,373: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 15:20:44,378: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 15:20:44,456: INFO: stage_02_prepare_model]: full untrained model is saved at artifacts\base_model\updated_base_model.h5
[2022-01-19 15:20:44,456: INFO: stage_02_prepare_model]: >>>>> stage preare model completed! : Base model is created.<<<<<

[2022-01-19 15:30:29,593: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 15:30:29,593: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 15:30:29,607: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 15:30:29,607: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 15:30:29,607: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 15:30:30,301: INFO: models]: full model summary Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         
=================================================================
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________

[2022-01-19 15:30:30,301: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 15:30:30,364: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 15:30:30,380: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 15:30:30,427: INFO: stage_02_prepare_model]: full untrained model is saved at artifacts\base_model\updated_base_model.h5
[2022-01-19 15:30:30,427: INFO: stage_02_prepare_model]: >>>>> stage preare model completed! : Base model is created.<<<<<

[2022-01-19 15:31:55,031: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 15:31:55,031: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 15:31:55,031: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 15:31:55,046: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 15:31:55,046: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 15:31:55,716: INFO: models]: full model summary Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         
=================================================================
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________

[2022-01-19 15:31:55,716: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 15:31:55,769: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 15:31:55,784: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 15:31:55,847: INFO: stage_02_prepare_model]: full untrained model is saved at artifacts\base_model\updated_base_model.h5
[2022-01-19 15:31:55,847: INFO: stage_02_prepare_model]: >>>>> stage preare model completed! : Base model is created.<<<<<

[2022-01-19 15:32:22,945: INFO: stage_02_prepare_model]: 
********************
[2022-01-19 15:32:22,945: INFO: stage_02_prepare_model]: >>>>> stage preare model started <<<<<
[2022-01-19 15:32:22,945: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 15:32:22,945: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 15:32:22,945: INFO: common]: created directory at: artifacts\base_model
[2022-01-19 15:32:23,627: INFO: models]: full model summary Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         
=================================================================
Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________

[2022-01-19 15:32:23,627: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2022-01-19 15:32:23,690: INFO: models]: VGG16 is successfully loaded and saved at artifacts\base_model\base_model.h5
[2022-01-19 15:32:23,706: INFO: models]: Custom layers to base model added and compiled.
[2022-01-19 15:32:23,768: INFO: stage_02_prepare_model]: full untrained model is saved at artifacts\base_model\updated_base_model.h5
[2022-01-19 15:32:23,768: INFO: stage_02_prepare_model]: >>>>> stage preare model completed! : Base model is created.<<<<<

[2022-01-19 16:23:16,912: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:23:16,912: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:23:16,912: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:23:16,912: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 16:23:16,912: ERROR: stage_03_prepare_callback]: 'CALLBACK_DIR'
Traceback (most recent call last):
  File "src/stage_03_prepare_callback.py", line 49, in <module>
    prepare_callback(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_03_prepare_callback.py", line 30, in prepare_callback
    callback_dir = os.path.join(artifacts_dir, artifacts['CALLBACK_DIR'])
KeyError: 'CALLBACK_DIR'
[2022-01-19 16:24:03,075: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:24:03,075: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:24:03,075: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:24:03,075: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 16:24:03,075: INFO: common]: created directory at: tensorboard_log_dir
[2022-01-19 16:24:03,075: INFO: common]: created directory at: checkpoint_dir
[2022-01-19 16:24:03,075: INFO: common]: created directory at: callback_dir
[2022-01-19 16:24:03,114: ERROR: stage_03_prepare_callback]: module 'os' has no attribute 'apth'
Traceback (most recent call last):
  File "src/stage_03_prepare_callback.py", line 49, in <module>
    prepare_callback(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_03_prepare_callback.py", line 37, in prepare_callback
    create_and_save_tb_callbacks(callback_dir, tensorboard_log_dir)
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\callbacks.py", line 19, in create_and_save_tb_callbacks
    tb_callback_path = os.apth.join(callbacks_dir,"tensorboard.cb.cb")
AttributeError: module 'os' has no attribute 'apth'
[2022-01-19 16:24:24,127: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:24:24,127: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:24:24,127: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:24:24,127: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-19 16:24:24,127: INFO: common]: created directory at: tensorboard_log_dir
[2022-01-19 16:24:24,127: INFO: common]: created directory at: checkpoint_dir
[2022-01-19 16:24:24,127: INFO: common]: created directory at: callback_dir
[2022-01-19 16:24:24,158: ERROR: stage_03_prepare_callback]: [Errno 2] No such file or directory: 'artifacts\\callbacks\\tensorboard.cb.cb'
Traceback (most recent call last):
  File "src/stage_03_prepare_callback.py", line 49, in <module>
    prepare_callback(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_03_prepare_callback.py", line 37, in prepare_callback
    create_and_save_tb_callbacks(callback_dir, tensorboard_log_dir)
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\callbacks.py", line 20, in create_and_save_tb_callbacks
    joblib.dump(tensorboard_callbacks, tb_callback_path)
  File "C:\Users\amiti\Desktop\MLops\DL\DVC-DL-TF\env\lib\site-packages\joblib\numpy_pickle.py", line 481, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\callbacks\\tensorboard.cb.cb'
[2022-01-19 16:28:14,188: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:28:14,188: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:28:14,188: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:28:14,188: INFO: common]: created directory at: tensorboard_log_dir
[2022-01-19 16:28:14,188: INFO: common]: created directory at: checkpoint_dir
[2022-01-19 16:28:14,188: INFO: common]: created directory at: callback_dir
[2022-01-19 16:28:14,219: ERROR: stage_03_prepare_callback]: [Errno 2] No such file or directory: 'artifacts\\callbacks\\tensorboard.cb.cb'
Traceback (most recent call last):
  File "src/stage_03_prepare_callback.py", line 48, in <module>
    prepare_callback(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_03_prepare_callback.py", line 36, in prepare_callback
    create_and_save_tb_callbacks(callback_dir, tensorboard_log_dir)
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\callbacks.py", line 21, in create_and_save_tb_callbacks
    joblib.dump(tensorboard_callbacks, tb_callback_path)
  File "C:\Users\amiti\Desktop\MLops\DL\DVC-DL-TF\env\lib\site-packages\joblib\numpy_pickle.py", line 481, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\callbacks\\tensorboard.cb.cb'
[2022-01-19 16:30:53,572: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:30:53,572: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:30:53,587: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:30:53,587: INFO: common]: created directory at: tensorboard_log_dir
[2022-01-19 16:30:53,587: INFO: common]: created directory at: checkpoint_dir
[2022-01-19 16:30:53,587: INFO: common]: created directory at: callbacks
[2022-01-19 16:30:53,603: ERROR: stage_03_prepare_callback]: [Errno 2] No such file or directory: 'artifacts\\callbacks\\tensorboard.cb.cb'
Traceback (most recent call last):
  File "src/stage_03_prepare_callback.py", line 48, in <module>
    prepare_callback(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_03_prepare_callback.py", line 36, in prepare_callback
    create_and_save_tb_callbacks(callback_dir, tensorboard_log_dir)
  File "c:\users\amiti\desktop\mlops\dl\dvc-dl-tf\src\utils\callbacks.py", line 21, in create_and_save_tb_callbacks
    joblib.dump(tensorboard_callbacks, tb_callback_path)
  File "C:\Users\amiti\Desktop\MLops\DL\DVC-DL-TF\env\lib\site-packages\joblib\numpy_pickle.py", line 481, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\callbacks\\tensorboard.cb.cb'
[2022-01-19 16:40:05,037: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:40:05,037: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:40:05,037: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:40:05,037: ERROR: stage_03_prepare_callback]: name 'callbacks_dir' is not defined
Traceback (most recent call last):
  File "src/stage_03_prepare_callback.py", line 48, in <module>
    prepare_callback(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_03_prepare_callback.py", line 33, in prepare_callback
    callbacks_dir
NameError: name 'callbacks_dir' is not defined
[2022-01-19 16:40:25,717: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:40:25,717: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:40:25,717: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:40:25,731: INFO: common]: created directory at: artifacts\tensorboard_log_dir
[2022-01-19 16:40:25,731: INFO: common]: created directory at: artifacts\checkpoints
[2022-01-19 16:40:25,731: INFO: common]: created directory at: artifacts\callbacks
[2022-01-19 16:40:25,749: INFO: callbacks]: Tensorboard callback is saved at artifacts\callbacks\tensorboard.cb.cb
[2022-01-19 16:40:25,749: INFO: callbacks]: Checkpoint callbacks are saved at artifacts\callbacks\tensorboard.cb.cb as binay file.
[2022-01-19 16:40:25,749: INFO: stage_03_prepare_callback]: >>>>> stage 2 completed!<<<<<

[2022-01-19 16:44:44,192: INFO: stage_03_prepare_callback]: 
********************
[2022-01-19 16:44:44,192: INFO: stage_03_prepare_callback]: >>>>> stage prepare_callback started <<<<<
[2022-01-19 16:44:44,192: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-19 16:44:44,192: INFO: common]: created directory at: artifacts\tensorboard_log_dir
[2022-01-19 16:44:44,192: INFO: common]: created directory at: artifacts\checkpoints
[2022-01-19 16:44:44,192: INFO: common]: created directory at: artifacts\callbacks
[2022-01-19 16:44:44,224: INFO: callbacks]: Tensorboard callback is saved at artifacts\callbacks\tensorboard.cb.cb
[2022-01-19 16:44:44,224: INFO: callbacks]: Checkpoint callbacks are saved at artifacts\callbacks\checkpoint.cb.cb as binay file.
[2022-01-19 16:44:44,224: INFO: stage_03_prepare_callback]: >>>>> stage 2 completed!<<<<<

